### ISSUE TITLE
Send response to client containing game state info

### ISSUE THREAD

**Issue by kcavicchio** [Scranton-Sleuths/scranton-sleuths#8]
Client needs to know:
* what the board looks like
* where they are
* what cards they have
* where the other players are

**Comment by EthanChe** [comment]
This may be done automatically when the state changes. Have to read the docs for this one.

**Comment by EthanChe** [comment]
The client can access the state whenever it wants, and it knows automatically when it gets updated. This is not needed, so closing issue;.
