### ISSUE TITLE
Move logic

### ISSUE THREAD

**Issue by kcavicchio** [Scranton-Sleuths/scranton-sleuths#9]
Client must figure out, while knowing where the players are etc, where the current user can move to on their turn.
Move logic:
* tbd
* if you were moved to another room by a player making a suggestion, you can choose to stay there and go straight to suggesting.

**Comment by EthanChe** [comment]
This logic should be done in the server. When the user clicks on a place to move to, a message will be sent to the server and the server will see if it is a valid move. If it is, the state of the Player will be updated. This state change automatically gets picked up by the Client. All the Client needs to do is translate the room name to x/y co-ordinates.

**Comment by EthanChe** [comment]
The client updates player locations correctly. It is up to the server to determine if it is a valid move.
